### ISSUE TITLE
Find Civil Rights Lawyers/Law Firms by Zipcode?

### ISSUE THREAD

**Issue by jbylund** [jbylund/impact-police-accountability#1]
Can maybe get from site like this: https://www.avvo.com/search/lawyer_search?utf8=%E2%9C%93&q=civil+rights&loc=02472

State bar associations sometimes have groups for certain types of law, that might be a good place to look.

**Comment by justinaustin** [comment]
I can take a stab at this one

**Comment by jbylund** [comment]
I started this running overnight and have a bunch of the data on S3 atm, next thing I'm going to do is pull the data into a db to possibly re-shape it a bit, and then figure out if it's too large to add to the repo.  You can take a look at what I ran here: https://github.com/jbylund/impact-police-accountability/blob/master/get_lawyer_info.py

**Comment by jbylund** [comment]
closed by #11, #12 and #15
