### ISSUE TITLE
Find Government (local/state/federal) Points of Contact

### ISSUE THREAD

**Issue by jbylund** [jbylund/impact-police-accountability#2]
Probably also by zipcode, e.g. user gives us a zip or some other sort of location data and we tell them:
```
Your local representatives are:
Position: Name / Website / Contact Info
...

Your State representatives are:
Position: Name / Website / Contact Info
...

Your Federal representatives are:
Position: Name / Website / Contact Info
...
```

TODO: where to source this data? (probably 1 answer for federal, 50 answers for state, and a gazillion answers for local, so prioritize federal/state then go in order of city population?)

**Comment by devo20216** [comment]
Not by zip code, so going to do a little more searching, but there is a Google Civic Information API that gives you local, state, and federal representatives by address.
http://developers.google.com/civic-information/docs/v2

**Comment by BWStearns** [comment]
@devo20216 you can actually just submit a zip code in the address field and skip the rest of the address. Try https://developers.google.com/civic-information/docs/v2/representatives/representativeInfoByAddress?apix_params=%7B%22address%22%3A%2202540%22%7D

**Comment by devo20216** [comment]
Nice, ok good catch. Then yeah I think this is the solution to move forward with. Already starting writing something for it
