### ISSUE TITLE
Form Letter to Government Officials

### ISSUE THREAD

**Issue by jbylund** [jbylund/impact-police-accountability#4]

**Comment by kaleagore** [comment]
Attempt at a draft [here](https://docs.google.com/document/d/1aGbNxeWWGg-7UZAVQjWpSEpzOQfT5zbDmABUx8vZfFE/edit)

**Comment by kaleagore** [comment]
Good source. We should link to this https://www.justice.gov/crt/addressing-police-misconduct-laws-enforced-department-justice

**Comment by jbylund** [comment]
> Attempt at a draft [here](https://docs.google.com/document/d/1aGbNxeWWGg-7UZAVQjWpSEpzOQfT5zbDmABUx8vZfFE/edit)

Can you post as a publicly accessible gist or something?

**Comment by kaleagore** [comment]
I can but it will loose all formatting and be more difficult to read

**Comment by jb-kensho** [comment]
Added as https://github.com/jbylund/impact-police-accountability/blob/master/FORM_LETTER.md
