### ISSUE TITLE
An About Page

### ISSUE THREAD

**Issue by jbylund** [jbylund/impact-police-accountability#5]
What is this all about, what are the problems we're trying to solve, who are we trying to help?

**Comment by willday4** [comment]
Draft for our About Us and an action statement where we could potentially link the form letter https://docs.google.com/document/d/1ufRz4Mmkk0OMju-sZxcubc61daqNQwRHJYlWqNt4pAY/edit

**Comment by jb-kensho** [comment]
Thanks, landed as https://github.com/jbylund/impact-police-accountability/blob/master/ABOUT.md
