### ISSUE TITLE
UI design

### ISSUE THREAD

**Issue by kaleagore** [jbylund/impact-police-accountability#6]
Diagram of ideal UI and user flow

**Comment by jb-kensho** [comment]
[added here](https://docs.google.com/presentation/d/1bcC--0LKL1uDntquWSkfkJpvb7RsrtBLg1W7kLdbM8I)

**Comment by jb-kensho** [comment]
[ui_wireframe.pdf](https://github.com/jbylund/impact-police-accountability/files/4903610/ui_wireframe.pdf)
