### ISSUE TITLE
Enumerate Backend Routes Needed

### ISSUE THREAD

**Issue by jbylund** [jbylund/impact-police-accountability#9]
What info do you imagine being included in the request? what does the backend need to get for you?

**Comment by dspoja** [comment]
Would this work?
Input as query parameter: zipcode=12345 OR state=VA or state=Virginia
Output:
```
{
	"government_resources": [{
		"organization": "ORG1",
		"contact_name": "Some Name",
		"phone_number": "111-222-3333",
		"address": "some address",
                "url": "some url"
	}],
	"law_enforcement_resources": [{
		"organization": "ORG1",
		"contact_name": "Some Name",
		"phone_number": "111-222-3333",
		"address": "some address",
                "url": "some url"
	}],
	"legal_resources": [{
		"organization": "ORG1",
		"contact_name": "Some Name",
		"phone_number": "111-222-3333",
		"address": "some address",
                "url": "some url"
	}]
}
```

**Comment by jbylund** [comment]
If we want to support the multiple layers of granularity we might want to accept just state, or just zipcode and return a larger set of resources if the query is coarser.  But this is probably enough for the front end to get rolling since they can just ignore anything they're not interested in.
